// SPDX-License-Identifier: AGPL-3.0-or-later

package worker

import (
	"context"
	"encoding/binary"
	"sort"

	"github.com/ai-continuity-platform/core/internal/compute/returnpath"
	rjm "github.com/ai-continuity-platform/core/internal/contracts/reconstruction_job_manifest"
	"github.com/ai-continuity-platform/core/internal/shared/crypto"
	shared_errors "github.com/ai-continuity-platform/core/internal/shared/errors"
	"github.com/ai-continuity-platform/core/internal/shared/ids"
	shared_time "github.com/ai-continuity-platform/core/internal/shared/time"
)

// GenerativeReconstructor is the V2 production R-11 backend — the real
// generative mechanism described in patents P1 §[0021]–[0023] and P2
// §[0018]. It swaps behind the frozen Reconstructor interface; no
// caller outside /internal/compute needs to change when the daemon
// flips from DeterministicReconstructor to this implementation.
//
// # Doctrinal framing
//
// The V1 DeterministicReconstructor expands a content-addressed digest
// by iterated SHA-256. Its output is cryptographically-bound to
// (manifest, components) but has no structural relationship to the
// input plaintexts: it is pseudo-random, not reconstructive. That was
// the correct choice for iteration 5 — it gave us a purely-doctrinal
// surface for the release-side and receive-side pipelines to build
// against.
//
// This implementation is different in kind. It trains a byte-level
// Markov model of order N over the canonical concatenation of the
// already-unsealed component plaintexts, then samples from the
// learned conditional distribution to produce exactly
// manifest.ExpectedOutputMaxBytes bytes. The output:
//
//   - reflects the statistical structure of the components: alphabet,
//     n-gram frequencies, and context-conditioned byte transitions;
//   - degrades measurably when the caller hands us a partial genome
//     (fewer components → fewer observed n-gram contexts → more
//     fallback to unigram + PRNG → measurable divergence from the
//     full-genome reconstruction; see the property tests);
//   - is still pure in its inputs: same (manifest, components) produce
//     byte-identical Bytes (the Markov sampler's randomness comes from
//     a deterministic SHA-256-driven stream seeded from the canonical
//     digestInputs, which is itself a pure function of the inputs).
//
// This is not a neural-network inference: we deliberately stay inside
// the codebase's existing cryptographic primitives (crypto.SHA256) so
// the swap is reviewable in a single diff. A future V3 can replace
// this implementation in turn — the frozen Reconstructor interface
// survives every such swap, which is the whole point of freezing it
// in iteration 5.
//
// # Freeze status
//
// GenerativeReconstructor is a NEW implementation in its own file. The
// frozen-identifier test in frozen_test.go scans only reconstruction.go;
// this file adds identifiers to the /internal/compute/worker package
// but does not change the contract surface enumerated there. The R-11
// interface method set (Reconstructor.Reconstruct) remains identical
// to V1 — V2 is a drop-in, not an amendment.
type GenerativeReconstructor struct {
	clock shared_time.Clock

	// order is the Markov context window in bytes. Order 3 is the
	// sweet spot for byte-level models on the corpus sizes we see in
	// staged-disclosure components: large enough to capture repeated
	// motifs ("the ", tensor-shard magic bytes), small enough that
	// context-lookups almost always hit the transition table for
	// realistic corpora. An operator who needs to tune this reaches
	// for a future Phase-3 configuration knob; iteration-7 ships the
	// default and does not expose the dial.
	order int

	// cancelCheckEvery is how many generated bytes we sample between
	// ctx.Err() polls. Small enough that a cancellation on a 1MB job
	// is observed within a few milliseconds; large enough that the
	// poll overhead is negligible compared to the sampling loop.
	cancelCheckEvery int
}

const (
	// defaultGenerativeOrder is the Markov context window. See the
	// struct-field comment for why 3.
	defaultGenerativeOrder = 3

	// defaultCancelCheckEvery is the cancellation-poll granularity.
	// 4096 bytes ≈ one page; fast enough for interactive cancellation,
	// cheap enough to be invisible in the sampling loop.
	defaultCancelCheckEvery = 4096
)

// NewGenerativeReconstructor builds a GenerativeReconstructor with
// production defaults: order-3 Markov context, 4 KiB cancellation
// polling granularity. A nil clock is rejected Structurally for the
// same reason the deterministic variant rejects it — any Reconstructor
// without an injected Clock would fall back to time.Now(), violating
// the monotonic-clock discipline in
// docs/doctrine/bootstrap-contracts.md §4.
func NewGenerativeReconstructor(clock shared_time.Clock) (*GenerativeReconstructor, error) {
	if clock == nil {
		return nil, shared_errors.Structural(
			shared_errors.CodeRequiredFieldMissing,
			"worker: GenerativeReconstructor requires a non-nil Clock",
			nil,
		)
	}
	return &GenerativeReconstructor{
		clock:            clock,
		order:            defaultGenerativeOrder,
		cancelCheckEvery: defaultCancelCheckEvery,
	}, nil
}

// Reconstruct implements the R-11 contract for the generative backend.
//
// The error taxonomy is identical to DeterministicReconstructor — same
// Structural refusals for malformed inputs, same Operational refusal
// for an already-cancelled context — so a caller catching classified
// errors does not need to differentiate by backend.
//
// Error behaviour
//
//   - CategoryStructural when inputs are malformed (empty components,
//     zero ExpectedOutputMaxBytes, duplicate ComponentID, empty IDs).
//   - CategoryOperational when the context is cancelled — either at
//     entry or part-way through the sampling loop.
//
// The generative backend has no Incident paths today. A future V3
// backend that performs attestation-sensitive inference could return
// CategoryIncident for a backend-internal tamper signal; the interface
// already permits that.
func (r *GenerativeReconstructor) Reconstruct(
	ctx context.Context,
	manifest rjm.ReconstructionJobManifest,
	components []ComponentMaterial,
) (returnpath.CandidateOutput, error) {
	var zero returnpath.CandidateOutput

	// Fast-fail on a cancelled context. See the same comment in
	// DeterministicReconstructor.Reconstruct: the worker loop relies
	// on us honouring cancellation on entry so a post-deadline job
	// does not even start sampling.
	if err := ctx.Err(); err != nil {
		return zero, shared_errors.Operational(
			shared_errors.CodeResourceExhausted,
			"worker: context already done at Reconstruct entry",
			err,
		)
	}

	// --- Structural validation -------------------------------------
	// This block is intentionally identical to the deterministic
	// variant. A single swap-in backend must reject the same set of
	// malformed inputs; diverging here would fracture the "swap is
	// invisible to callers" contract.
	if manifest.ManifestID.IsZero() {
		return zero, shared_errors.Structural(
			shared_errors.CodeRequiredFieldMissing,
			"worker: manifest.ManifestID is empty", nil)
	}
	if manifest.SessionID.IsZero() {
		return zero, shared_errors.Structural(
			shared_errors.CodeRequiredFieldMissing,
			"worker: manifest.SessionID is empty", nil)
	}
	if manifest.ExpectedOutputMaxBytes == 0 {
		return zero, shared_errors.Structural(
			shared_errors.CodeFieldValueInvalid,
			"worker: manifest.ExpectedOutputMaxBytes must be > 0", nil)
	}
	if len(components) == 0 {
		return zero, shared_errors.Structural(
			shared_errors.CodeRequiredFieldMissing,
			"worker: at least one component material required", nil)
	}
	seen := make(map[ids.ComponentID]struct{}, len(components))
	for _, c := range components {
		if c.ComponentID.IsZero() {
			return zero, shared_errors.Structural(
				shared_errors.CodeRequiredFieldMissing,
				"worker: ComponentMaterial.ComponentID is empty", nil)
		}
		if _, dup := seen[c.ComponentID]; dup {
			return zero, shared_errors.Structural(
				shared_errors.CodeFieldValueInvalid,
				"worker: duplicate ComponentID in components", nil)
		}
		seen[c.ComponentID] = struct{}{}
	}

	// --- Canonical ordering ----------------------------------------
	// Same sort key as DeterministicReconstructor: (SequenceIndex,
	// ComponentID). Callers that hand us components in random order
	// must produce byte-identical output as callers that hand us the
	// canonical order — this reflects the doctrinal property that
	// identity is defined by the staged-disclosure sequence, not by
	// the in-memory slice.
	sorted := append([]ComponentMaterial(nil), components...)
	sort.SliceStable(sorted, func(i, j int) bool {
		if sorted[i].SequenceIndex != sorted[j].SequenceIndex {
			return sorted[i].SequenceIndex < sorted[j].SequenceIndex
		}
		return sorted[i].ComponentID < sorted[j].ComponentID
	})

	// --- Training corpus + seed ------------------------------------
	// Both are pure functions of (manifest, sorted). The corpus is
	// what the Markov model learns from; the seed drives the
	// deterministic sampling trajectory. Any change to any input
	// ripples into BOTH the corpus (shifting n-gram transitions) and
	// the seed (shifting the PRNG stream). That double-dependency is
	// what gives the property tests their one-bit-flip sensitivity
	// without us having to do anything clever at the sampler level.
	corpus := buildGenerativeCorpus(manifest, sorted)
	seed := digestInputs(manifest, sorted)
	model := buildNGramModel(corpus, r.order)
	prng := newStreamPRNG(seed[:])

	// --- Generation loop -------------------------------------------
	n := manifest.ExpectedOutputMaxBytes
	out := make([]byte, 0, n)

	// Initial context. If the corpus is shorter than r.order, we pad
	// with PRNG bytes so the window is well-defined. (This branch is
	// hit only by pathologically-tiny test fixtures; a realistic
	// staged-disclosure component is at least kilobytes.)
	ctxWin := make([]byte, r.order)
	if len(corpus) >= r.order {
		copy(ctxWin, corpus[:r.order])
	} else {
		copy(ctxWin, corpus)
		for i := len(corpus); i < r.order; i++ {
			ctxWin[i] = prng.Byte()
		}
	}

	sinceCheck := 0
	for uint64(len(out)) < n {
		if sinceCheck >= r.cancelCheckEvery {
			if err := ctx.Err(); err != nil {
				return zero, shared_errors.Operational(
					shared_errors.CodeResourceExhausted,
					"worker: context cancelled during generative sampling",
					err,
				)
			}
			sinceCheck = 0
		}

		b := model.sample(ctxWin, prng)
		out = append(out, b)

		// Shift the context window forward by one byte.
		copy(ctxWin, ctxWin[1:])
		ctxWin[r.order-1] = b
		sinceCheck++
	}

	return returnpath.CandidateOutput{
		ManifestID: manifest.ManifestID,
		SessionID:  manifest.SessionID,
		OutputKind: manifest.ExpectedOutputKind,
		Bytes:      out,
		ProducedAt: r.clock.Now(),
	}, nil
}

// ---- corpus construction --------------------------------------------------

// buildGenerativeCorpus concatenates component plaintexts (already in
// canonical order) into the training corpus. A 2-byte separator
// derived from manifest.ManifestID sits between components: this
// ensures the n-gram transitions learned from two different manifests
// differ in their inter-component boundaries, even if the component
// plaintexts happened to be identical. The separator is advisory, not
// authenticated — manifest-identity sensitivity is already enforced
// cryptographically through digestInputs; the separator is the
// SECONDARY path through which ManifestID influences the output
// (reinforcing, not substituting).
func buildGenerativeCorpus(manifest rjm.ReconstructionJobManifest, sorted []ComponentMaterial) []byte {
	sepHash := crypto.SHA256([]byte(manifest.ManifestID))
	sep := sepHash[:2]

	total := 0
	for _, c := range sorted {
		total += len(c.Plaintext)
	}
	if len(sorted) > 1 {
		total += len(sep) * (len(sorted) - 1)
	}

	buf := make([]byte, 0, total)
	for i, c := range sorted {
		if i > 0 {
			buf = append(buf, sep...)
		}
		buf = append(buf, c.Plaintext...)
	}
	return buf
}

// ---- Markov n-gram model --------------------------------------------------

// ngramModel is an order-K byte-level Markov model learned from a
// training corpus. trans maps a length-K context (encoded as a string
// key for map lookups) to a multiset of observed next-bytes. Storing
// the multiset (rather than a probability vector) keeps the empirical
// distribution exact and lets us sample in O(1) per byte.
//
// Fallback strategy when a context is unseen:
//
//  1. Unigram: sample uniformly from the whole corpus (preserves the
//     corpus's overall byte histogram).
//  2. PRNG: sample a uniformly-random byte. Reached only when the
//     corpus is empty — a contingency the validation layer prevents
//     but we keep for defence-in-depth.
type ngramModel struct {
	order   int
	trans   map[string][]byte
	unigram []byte
}

// buildNGramModel scans the corpus with a sliding order-K window and
// accumulates transition observations. Returns a non-nil model even
// for empty or too-short corpora; sample() handles the fallbacks.
func buildNGramModel(corpus []byte, order int) *ngramModel {
	m := &ngramModel{
		order:   order,
		trans:   make(map[string][]byte),
		unigram: corpus,
	}
	if len(corpus) <= order {
		return m
	}
	// Walk every position where a context + next-byte pair exists.
	for i := 0; i+order < len(corpus); i++ {
		ctx := string(corpus[i : i+order])
		next := corpus[i+order]
		m.trans[ctx] = append(m.trans[ctx], next)
	}
	return m
}

// sample returns the next byte given the current context window and
// the PRNG. The fallback chain is context → unigram → PRNG; see the
// ngramModel doc for rationale.
func (m *ngramModel) sample(ctx []byte, prng *streamPRNG) byte {
	if m != nil {
		if nexts, ok := m.trans[string(ctx)]; ok && len(nexts) > 0 {
			return nexts[prng.Intn(len(nexts))]
		}
		if len(m.unigram) > 0 {
			return m.unigram[prng.Intn(len(m.unigram))]
		}
	}
	return prng.Byte()
}

// ---- deterministic stream PRNG --------------------------------------------

// streamPRNG is a deterministic byte-stream derived from a SHA-256
// seed. Construction: each 32-byte block is SHA-256(seed || counter),
// with counter advancing by one per block. Bytes are consumed from
// the current block; when exhausted, the next block is computed.
//
// Why not math/rand/v2's ChaCha8? ChaCha8 would give us a
// library-provided uniform stream with a slightly nicer interface,
// but at the cost of introducing a second cryptographic primitive in
// this file. The codebase's convention (see /internal/shared/crypto)
// is that every random or content-addressed derivation funnels
// through crypto.SHA256; we follow that convention so a reviewer can
// audit the full sampling stack by reading exactly one hash function.
type streamPRNG struct {
	seed    [crypto.HashSize]byte
	block   [crypto.HashSize]byte
	pos     int
	counter uint64
}

// newStreamPRNG initialises the PRNG from a seed. The seed slice need
// not be exactly HashSize; we re-hash it so the stream depends on the
// full input regardless of length.
func newStreamPRNG(seed []byte) *streamPRNG {
	h := crypto.SHA256(seed)
	p := &streamPRNG{seed: h, pos: crypto.HashSize}
	return p
}

// refill computes the next 32-byte block from (seed || counter) and
// resets the read cursor. Advances the counter so the following block
// is distinct from the current one.
func (p *streamPRNG) refill() {
	buf := make([]byte, 0, crypto.HashSize+8)
	buf = append(buf, p.seed[:]...)
	var ctrBuf [8]byte
	binary.BigEndian.PutUint64(ctrBuf[:], p.counter)
	buf = append(buf, ctrBuf[:]...)
	p.block = crypto.SHA256(buf)
	p.pos = 0
	p.counter++
}

// Byte returns the next byte from the stream.
func (p *streamPRNG) Byte() byte {
	if p.pos >= crypto.HashSize {
		p.refill()
	}
	b := p.block[p.pos]
	p.pos++
	return b
}

// Uint64 returns the next 8 bytes as a big-endian uint64.
func (p *streamPRNG) Uint64() uint64 {
	var buf [8]byte
	for i := 0; i < 8; i++ {
		buf[i] = p.Byte()
	}
	return binary.BigEndian.Uint64(buf[:])
}

// Intn returns a uniform random int in [0, n). n must be positive;
// a zero or negative n is a programming error and panics — callers
// in this package only pass positive ints (len of a non-empty slice).
//
// The bias from taking Uint64() % uint64(n) is at most n/2^64, which
// for n ≤ 2^20 (largest plausible corpus length in our tests) is
// below 2^-44 — statistically undetectable. We accept the bias to
// keep the function body short and reviewable.
func (p *streamPRNG) Intn(n int) int {
	if n <= 0 {
		panic("streamPRNG.Intn: n must be positive")
	}
	return int(p.Uint64() % uint64(n))
}

// Compile-time assertion that GenerativeReconstructor satisfies the
// frozen Reconstructor interface. Paired with the same assertion in
// reconstruction.go for DeterministicReconstructor: both implementations
// must continue to conform to the interface frozen_test.go locks.
var _ Reconstructor = (*GenerativeReconstructor)(nil)
