// SPDX-License-Identifier: AGPL-3.0-or-later

package orchestration

import (
	"testing"

	"github.com/stretchr/testify/require"
)

func TestState_String_Stable(t *testing.T) {
	t.Parallel()
	cases := map[State]string{
		StateUnstarted:           "unstarted",
		StateRequest:             "request",
		StateTrust:               "trust",
		StateSession:             "session",
		StateDisclosure:          "disclosure",
		StateExternalCompute:     "external_compute",
		StateReturn:              "return",
		StateValidation:          "validation",
		StateRelease:             "release",
		StateAudit:               "audit",
		StateReleaseAuthorized:   "release_authorized",
		StateIncidentTerminated:  "incident_terminated",
		StateCrossCloudHandshake: "cross_cloud_handshake",
	}
	for s, want := range cases {
		require.Equal(t, want, s.String(), "state identifier must be stable (audit payloads depend on it)")
	}
}

func TestIsTerminal(t *testing.T) {
	t.Parallel()
	require.True(t, StateReleaseAuthorized.IsTerminal())
	require.True(t, StateIncidentTerminated.IsTerminal())

	nonTerminal := []State{
		StateUnstarted, StateRequest, StateTrust, StateSession,
		StateDisclosure, StateExternalCompute, StateReturn,
		StateValidation, StateRelease, StateAudit,
	}
	for _, s := range nonTerminal {
		require.False(t, s.IsTerminal(), "state %s must not be terminal", s)
	}
}

func TestIsOperational(t *testing.T) {
	t.Parallel()
	require.False(t, StateUnstarted.IsOperational())
	require.False(t, StateReleaseAuthorized.IsOperational())
	require.False(t, StateIncidentTerminated.IsOperational())

	for _, s := range []State{StateRequest, StateTrust, StateSession, StateDisclosure, StateExternalCompute, StateReturn, StateValidation, StateRelease, StateAudit, StateCrossCloudHandshake} {
		require.True(t, s.IsOperational(), "state %s must be operational", s)
	}
}

// --- Phase 4 cross-cloud transitions -------------------------------

func TestCrossCloudHandshake_TransitionsRespectADR0006(t *testing.T) {
	t.Parallel()
	// Stage 8 → Stage 8.5 (opt-in to cross-cloud).
	require.True(t, CanTransition(StateRelease, StateCrossCloudHandshake, "cross_cloud.initiated"))

	// Stage 8.5 → Stage 9 (handshake successful, token dispatched).
	require.True(t, CanTransition(StateCrossCloudHandshake, StateAudit, "cross_cloud.token_dispatched"))

	// Stage 8.5 → IncidentTerminated (attestation failure or policy denial).
	// This arc is generated by the IncidentCapableStates loop.
	require.True(t, CanTransition(StateCrossCloudHandshake, StateIncidentTerminated, "incident.detected"))
}

func TestCrossCloudHandshake_PreservesLocalReleasePath(t *testing.T) {
	t.Parallel()
	// The original Stage 8 → Stage 9 transition for local single-TEE
	// flows MUST still be valid — cross-cloud is opt-in, not mandatory.
	require.True(t, CanTransition(StateRelease, StateAudit, "decision.signed"))
}

func TestCrossCloudHandshake_IncludedInIncidentCapable(t *testing.T) {
	t.Parallel()
	found := false
	for _, s := range IncidentCapableStates {
		if s == StateCrossCloudHandshake {
			found = true
			break
		}
	}
	require.True(t, found, "StateCrossCloudHandshake must be incident-capable per ADR 0006")
}

func TestCrossCloudHandshake_IsNotTerminal(t *testing.T) {
	t.Parallel()
	require.False(t, StateCrossCloudHandshake.IsTerminal())
}

func TestCrossCloudHandshake_LegalTransitionsList(t *testing.T) {
	t.Parallel()
	transitions := LegalTransitions(StateCrossCloudHandshake)
	// Expect: → StateAudit (token_dispatched) AND → StateIncidentTerminated (incident_detected).
	require.GreaterOrEqual(t, len(transitions), 2, "at least 2 transitions out of cross-cloud handshake")

	hasAudit := false
	hasIncident := false
	for _, tr := range transitions {
		if tr.To == StateAudit && tr.Trigger == "cross_cloud.token_dispatched" {
			hasAudit = true
		}
		if tr.To == StateIncidentTerminated && tr.Trigger == "incident.detected" {
			hasIncident = true
		}
	}
	require.True(t, hasAudit, "must have transition to StateAudit on token_dispatched")
	require.True(t, hasIncident, "must have transition to StateIncidentTerminated on incident.detected")
}

func TestCrossCloudHandshake_StateRelease_HasBothBranches(t *testing.T) {
	t.Parallel()
	// From StateRelease both branches must be available:
	// (1) decision.signed → StateAudit (local single-TEE flow)
	// (2) cross_cloud.initiated → StateCrossCloudHandshake (cross-cloud flow)
	transitions := LegalTransitions(StateRelease)
	hasLocal := false
	hasCrossCloud := false
	for _, tr := range transitions {
		if tr.To == StateAudit && tr.Trigger == "decision.signed" {
			hasLocal = true
		}
		if tr.To == StateCrossCloudHandshake && tr.Trigger == "cross_cloud.initiated" {
			hasCrossCloud = true
		}
	}
	require.True(t, hasLocal, "local single-TEE branch (decision.signed → StateAudit) must remain valid")
	require.True(t, hasCrossCloud, "cross-cloud branch (cross_cloud.initiated → StateCrossCloudHandshake) must be added")
}

func TestHappyPath_CanTransition(t *testing.T) {
	t.Parallel()
	// End-to-end happy path through all nine stages.
	steps := []struct {
		from, to State
		trigger  string
	}{
		{StateUnstarted, StateRequest, "request.received"},
		{StateRequest, StateTrust, "request.validated"},
		{StateTrust, StateSession, "attestation.allow"},
		{StateSession, StateDisclosure, "session.issued"},
		{StateDisclosure, StateExternalCompute, "manifest.dispatched"},
		{StateExternalCompute, StateReturn, "candidate.received"},
		{StateReturn, StateValidation, "return.accepted"},
		{StateValidation, StateRelease, "validation.completed"},
		{StateRelease, StateAudit, "decision.signed"},
		{StateAudit, StateReleaseAuthorized, "audit.sealed.release_true"},
	}
	for _, step := range steps {
		require.True(t, CanTransition(step.from, step.to, step.trigger), "happy-path arc %s → %s [%s] must exist", step.from, step.to, step.trigger)
	}
}

func TestIncidentArcs_ExistFromEveryOperationalStage(t *testing.T) {
	t.Parallel()
	for _, s := range IncidentCapableStates {
		require.True(t, CanTransition(s, StateIncidentTerminated, "incident.detected"), "state %s must allow incident termination", s)
	}
}

func TestNoTransitionsOutOfTerminal(t *testing.T) {
	t.Parallel()
	for _, terminal := range []State{StateReleaseAuthorized, StateIncidentTerminated} {
		require.Empty(t, LegalTransitions(terminal), "terminal state %s must have no outgoing transitions", terminal)
	}
}

func TestCanTransition_IllegalReturnsFalse(t *testing.T) {
	t.Parallel()
	// Skip trust → audit directly — that bypasses session issuance.
	require.False(t, CanTransition(StateTrust, StateAudit, ""))
	// Validation → Session is a backward edge, must not exist.
	require.False(t, CanTransition(StateValidation, StateSession, ""))
	// Unknown trigger on an otherwise legal arc.
	require.False(t, CanTransition(StateRequest, StateTrust, "not.a.real.trigger"))
}

func TestCanTransition_EmptyTriggerMatchesAny(t *testing.T) {
	t.Parallel()
	require.True(t, CanTransition(StateRequest, StateTrust, ""))
}

func TestTransitionTable_NonEmpty(t *testing.T) {
	t.Parallel()
	require.NotEmpty(t, TransitionTable)
	require.Greater(t, len(TransitionTable), len(happyPathTransitions), "incident arcs must have been appended")
}

func TestLegalTransitions_Request(t *testing.T) {
	t.Parallel()
	got := LegalTransitions(StateRequest)
	// StateRequest has: → StateTrust (happy), → StateIncidentTerminated (incident)
	require.Len(t, got, 2)
}
