// SPDX-License-Identifier: AGPL-3.0-or-later

// Package exposure holds the fail-closed network-exposure rules every
// daemon applies to its listeners: which listen addresses are reachable
// only from the local host, and how strong a bearer token must be once
// a listener is reachable from anywhere else. Keeping one copy means the
// daemons cannot drift apart on what "loopback" or "strong enough" means.
package exposure

import (
	"fmt"
	"net"
	"os"
	"strings"
)

// MinBearerTokenLen is the minimum bearer-token length accepted on a
// listener reachable beyond the local host (32 hex characters = 128
// bits of entropy when generated by the deploy keygen).
const MinBearerTokenLen = 32

// IsLoopback reports whether a host:port listen address is reachable
// only from the local host. An empty host, "0.0.0.0", or "::" binds
// every interface and is therefore NOT loopback; any hostname other
// than "localhost" is treated as non-loopback because it may resolve to
// a routable address. An address that does not parse is not loopback.
func IsLoopback(listenAddress string) bool {
	host, _, err := net.SplitHostPort(listenAddress)
	if err != nil {
		return false
	}
	return IsLoopbackHost(host)
}

// IsLoopbackHost reports whether host (a bare hostname or IP, as in
// url.URL.Hostname) names the local host only: "localhost" or a
// loopback IP. Any other hostname may resolve anywhere.
func IsLoopbackHost(host string) bool {
	if host == "localhost" {
		return true
	}
	ip := net.ParseIP(host)
	return ip != nil && ip.IsLoopback()
}

// ReadTokenFile returns the bearer token stored at path, with
// surrounding whitespace trimmed. An empty file is an error: a daemon
// told to authenticate with a token must never fall back to none.
func ReadTokenFile(path string) (string, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return "", fmt.Errorf("read bearer token file: %w", err)
	}
	token := strings.TrimSpace(string(raw))
	if token == "" {
		return "", fmt.Errorf("bearer token file %q is empty", path)
	}
	return token, nil
}
